name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set PYTHONPATH to include the 'Case Study/src' directory
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/Case\ Study/src" >> $GITHUB_ENV

      - name: List files in repository
        run: |
          ls -l "Case Study"
          ls -l "Case Study/src"
          ls -l "Case Study/tests"

      - name: Run Tests
        run: pytest "Case Study/tests/" -v